### ISSUE TITLE
PARALLEL_REQUESTS=true has no effect on gguf models

### ISSUE THREAD

**Issue by phebing** [mudler/LocalAI#1467]
**LocalAI version:**
image: quay.io/go-skynet/local-ai:v2.0.0-cublas-cuda12

**Environment, CPU architecture, OS, and Version:**
Linux dev-aisrv01 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

**Describe the bug**
We tried to run parallel requests against the codellama https://huggingface.co/TheBloke/CodeLlama-34B-Instruct-GGUF model but that did not work. It seems only parallel requests on different models are working, requests against the same model are queued and responds arrive one after the other.

In our .env we set `PARALLEL_REQUESTS=true` but the logs say 
```
DBG Loading Model codellama-34b-instruct.Q4_K_M.gguf with gRPC (file: /models/codellama-34b-instruct.Q4_K_M.gguf) (backend: llama): 
...  
singleActiveBackend:false parallelRequests:false}
```
The backend is specified as `backend: llama` in the models yml file.

If we specify the backend as `backend: llama-cpp` then the log says
```
DBG Loading Model codellama-34b-instruct.Q4_K_M.gguf with gRPC (file: /models/codellama-34b-instruct.Q4_K_M.gguf) (backend: llama-cpp): 
...
 parallelRequests:true}
 ```
 but with llama-cpp we get the error
 ```
  DBG GRPC(codellama-34b-instruct.Q4_K_M.gguf-127.0.0.1:45563): stderr CUDA error 1 at /build/backend/cpp/llama/llama.cpp/ggml-cuda.cu:7043: invalid argument
  ```
  
  How can we enable `PARALLEL_REQUESTS=true` with `backend: llama`?
  Or what can we do to run the gguf model on `backend: llama-cpp` ?

**To Reproduce**

**Expected behavior**
`PARALLEL_REQUESTS=true` enables parallel requests in llama backend.

**Logs**

**Additional context**

**Comment by phebing** [comment]
Back from vacation.
Ok I feel a bit misunderstood:

> To enable parallel requests with backend: llama, you can try setting PARALLEL_REQUESTS=true in your .env file and restarting the server. This should allow multiple requests to be processed simultaneously on different models.

From my experience and also after testing again `PARALLEL_REQUESTS=true` should not be the setting to allow simultaneous requests on different models, right? That should be `SINGLE_ACTIVE_BACKEND=false`
Tested again with `SINGLE_ACTIVE_BACKEND=false` and `PARALLEL_REQUESTS=false` and was able to run simultaneous requests on different models.

I would like to run simultaneous requests on a single model.
And this seems to not be possible with the llama backend, right? (since the `PARALLEL_REQUESTS=true` seems to be ignored)

That is why I thought to choose llama-cpp.
Setting `REBUILD=true`, `BUILD_TYPE=cuBLAS` and `CMAKE_ARGS="-DLLAMA_F16C=OFF -DLLAMA_AVX512=OFF -DLLAMA_AVX2=OFF -DLLAMA_AVX=OFF -DLLAMA_FMA=OFF"` resulted in lots of `undefined reference to `__cudaRegisterFunction'` and other cuda related stuff. I guess I would need to install CUDA dependencies for that, but I am already using the `image: quay.io/go-skynet/local-ai:v2.0.0-cublas-cuda12`... so shouldn`t they be there already?

Any other ideas to try out to get parallel requests on a single model up and running?

**Comment by phebing** [comment]
Upgrading to 2.4.0 fixed it!
But i am still confused:
Now the model uses the llama-cpp backend while i am still using `backend: llama` in the models yaml file.

Also the model (codellama) generates a response that is repeating itself. 
Had this before and fixed it by setting `rope_freq_base: 1000000` and `rope_freq_scale: 1.0` for the model. Maybe that one broke again when switching from 2.0.0 to 2.4.0, but that is a different story.

To the original Problem:
Testing another gguf model on 2.4.0 with llama specified uses llama-cpp and parallel_requests:true and was able to produce parallel streaming responses :D

Thanks for your work! If you have any ideas on how to fix the codellama repeating itself bug again then please leave a reply.
Otherwise the original topic is fixed, so feel free to close this one

**Comment by tauven** [comment]
Hi @phebing, are you able to share your configuration, including enviroment parameters and model yml?
I'm still not able to make parallel requests with the llama backend or llama-cpp backend, also not sure if the is really a difference between these to settings...

My debug logs are:

9:33PM DBG Loading Model dolphin-2.6-mistral-7b.Q4_0.gguf with gRPC (file: /Users/xxx/Applications/LocalAI/models/dolphin-2.6-mistral-7b.Q4_0.gguf) (backend: llama-cpp): {backendString:llama model:dolphin-2.6-mistral-7b.Q4_0.gguf threads:6 assetDir:/tmp/localai/backend_data context:{emptyCtx:{}} gRPCOptions:0x14000256780 externalBackends:map[] grpcAttempts:20 grpcAttemptsDelay:2 singleActiveBackend:false parallelRequests:true}

That looks fine too me, but if i start 2 or more requests they are done sequentially order and not parallel.

started localai with this parameters:
`SINGLE_ACTIVE_BACKEND=false PYTHON_GRPC_MAX_WORKERS=8 LLAMACPP_PARALLEL=8 PARALLEL_REQUESTS=true DEBUG=true ./local-ai`

Thank you!

**Comment by phebing** [comment]
Sure. Here you go @tauven 
My .env file looks like this
```
BUILD_TYPE=cublas
MODELS_PATH=/models
THREADS=12

### Python backends GRPC max workers
### Default number of workers for GRPC Python backends.
### This actually controls wether a backend can process multiple requests or not.
PYTHON_GRPC_MAX_WORKERS=12

### Define the number of parallel LLAMA.cpp workers (Defaults to 1)
LLAMACPP_PARALLEL=12

### Enable to run parallel requests
PARALLEL_REQUESTS=true
SINGLE_ACTIVE_BACKEND=false
```

My mixtral.yaml for the model:
```
name: mixtral

parameters:
  model: mixtral-8x7b-instruct-v0.1.Q6_K.gguf # from huggingface theBloke
  temperature: 0.2 
  top_k: 40
  top_p: 0.95
  frequency_penalty: 1.1
  batch: 512
  tfz: 1.0
  max_tokens: 1024

context_size: 4096
backend: llama 
gpu_layers: 90
f16: true
mmap: true

template:
  # see https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1#instruction-format
  completion: |
    [INST] {{.Input}} [/INST]
  chat: |
    {{.Input}}
  chat_message: |
    {{if eq .RoleName "assistant"}}{{.Content}}{{else}}[INST]
    {{if .Content}}{{.Content}}{{end}}
    [/INST] 
    {{end}}

stopwords:
  - </s>
```

**Comment by tauven** [comment]
Thanks @phebing !
I basically have the same settings, but using build type = metal ... will try yours!

**Comment by tauven** [comment]
I have tried your settings, but sadly no change.
But I have noticed something:
If I create 2 streaming requests before the model is loaded, they are processed in parallel. This shows that it is possible to process several parallel requests against the same model at the same time. But all subsequent parallel requests are processed one after the other.  This means that requests that are created before the model is loaded are processed correctly in parallel after the model has been loaded. Unfortunately, it no longer works after that.

I'm on the current version:

And building from source with: 
make BUILD_TYPE=metal BUILD_GRPC_FOR_BACKEND_LLAMA=true GRPC_BACKENDS=backend-assets/grpc/llama-cpp build

starting with the following script:

```
#!/bin/zsh

export THREADS=12
export PYTHON_GRPC_MAX_WORKERS=12
export LLAMACPP_PARALLEL=12 
export PARALLEL_REQUESTS=true 
export DEBUG=true 
export SINGLE_ACTIVE_BACKEND=false
export F16=true

export WATCHDOG_IDLE=true
export WATCHDOG_BUSY=true
export WATCHDOG_IDLE_TIMEOUT=5m
export WATCHDOG_BUSY_TIMEOUT=5m

./local-ai --galleries '[{"name":"SB", "url":"http://localhost:8081/index.yaml"}]'
```

Logs:
```
9:43PM INF Starting LocalAI using 12 threads, with models path: /Users/xxx/Applications/LocalAI/models
9:43PM INF LocalAI version: v2.5.1-25-g52c9a7f (52c9a7f45da5f4ea8ee91ba06a32d336006d12ba)
9:43PM INF Preloading models from /Users/xxx/Applications/LocalAI/models
...
 ┌───────────────────────────────────────────────────┐ 
 │                   Fiber v2.50.0                   │ 
 │               http://127.0.0.1:8080               │ 
 │       (bound on host 0.0.0.0 and port 8080)       │ 
 │                                                   │ 
 │ Handlers ............ 74  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ............. 41697 │ 
 └───────────────────────────────────────────────────┘ 
...

9:44PM DBG Loading Model dolphin-2.6-mistral-7b.Q4_0.gguf with gRPC (file: /Users/xxx/Applications/LocalAI/models/dolphin-2.6-mistral-7b.Q4_0.gguf) (backend: llama-cpp): {backendString:llama-cpp model:dolphin-2.6-mistral-7b.Q4_0.gguf threads:4 assetDir:/tmp/localai/backend_data context:{emptyCtx:{}} gRPCOptions:0x140002fe780 externalBackends:map[] grpcAttempts:20 grpcAttemptsDelay:2 singleActiveBackend:false parallelRequests:true}

```

If there is anything I can do to help, please let me know.

**Comment by tauven** [comment]
Could it be that there is a missing parameter for llama.cpp? When I start the server from llama.cpp in the following way, I get the behaviour I want:

./server -m ../LocalAI/models/dolphin-2.6-mistral-7b.Q4_K_M.gguf -c 2048 --port 8080 --parallel 4 -cb

It needs the parameter --parallel and --cont-batching
Then I can actually execute several requests in parallel.

**Comment by tauven** [comment]
I merged the changes from the current llama.cpp/master/examples/server/server.cpp into LocalAI/tree/master/backend/cpp/llama/grpc-server.cpp and hardcoded cont_batching to true.
I now get parallel streaming responses.

I do not know if this is the right thing to do but it seems to work ;-)

**Comment by mudler** [comment]
thanks @tauven for digging into it :100: appreciated
